spring.application.name=SpringBootJDBC


spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:mysql://localhost:3306/practice5
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

server.port=8084